# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroupsApp', '0005_group_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(default='comment...')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.ManyToManyField(to='CommentsApp.Comment'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
