# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0006_auto_20161208_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='comments',
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
