# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0004_auto_20161204_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='speciality',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
