# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_auto_20161205_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='project',
            name='createdBy',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
