# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0008_projectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
