# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0002_auto_20161112_1935'),
        ('CompaniesApp', '0002_auto_20161109_2034'),
    ]

    operations = [
    ]
