# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_myuser_test_field2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='test_field',
            new_name='university_name',
        ),
    ]
