# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0012_auto_20161201_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='contact_info',
            new_name='home_address',
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
