# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0013_auto_20161202_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about_user',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
