# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0014_myuser_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
