# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0016_auto_20161204_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
