# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0018_teacher_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='photo',
            new_name='teacherPhoto',
        ),
    ]
