# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0021_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default=0, upload_to='static/teacherimages'),
        ),
    ]
