# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0022_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
    ]
