# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0024_auto_20161208_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='project',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
