# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0026_auto_20161208_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='project',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='projectID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
